# Generated by Django 4.2 on 2023-07-17 09:34

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique_request',
            name='country',
            field=django_countries.fields.CountryField(default='united state', max_length=2),
            preserve_default=False,
        ),
    ]
