# Generated by Django 4.2 on 2023-05-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0002_main_category_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
