# Generated by Django 4.2 on 2023-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0002_boutique_request_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique_request',
            name='country',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='boutique_request',
            name='products_image1',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boutique_request',
            name='products_image2',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boutique_request',
            name='products_image3',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boutique_request',
            name='products_image4',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
    ]
