# Generated by Django 4.2 on 2023-05-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0003_category_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='False'),
        ),
    ]
