# Generated by Django 4.2 on 2023-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0004_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands_logo', models.ImageField(blank=True, default=False, null=True, upload_to='')),
            ],
        ),
    ]
