# Generated by Django 4.2 on 2023-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0005_counter_top_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_brands',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
