# Generated by Django 4.2 on 2023-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0006_top_brands_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
