# Generated by Django 4.2 on 2023-08-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0007_item_about_your_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
