# Generated by Django 4.2 on 2023-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0007_payment_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutUserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('lists', models.ManyToManyField(to='Like.sub_category')),
            ],
        ),
    ]
