# Generated by Django 4.2 on 2023-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0008_item_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
