# Generated by Django 4.2 on 2023-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0008_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
