# Generated by Django 4.2 on 2023-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0008_payoutuserlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutuserlist',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='payoutuserlist',
            name='name',
        ),
        migrations.AddField(
            model_name='payoutuserlist',
            name='note',
            field=models.CharField(default='Thanks for your patronage!', max_length=200),
        ),
        migrations.AddField(
            model_name='payoutuserlist',
            name='notification_language',
            field=models.CharField(default='en-US', max_length=200),
        ),
        migrations.AddField(
            model_name='payoutuserlist',
            name='receiver',
            field=models.CharField(default='receiver@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='payoutuserlist',
            name='recipient_type',
            field=models.CharField(default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='payoutuserlist',
            name='recipient_wallet',
            field=models.CharField(default='RECIPIENT_SELECTED', max_length=200),
        ),
        migrations.AddField(
            model_name='payoutuserlist',
            name='sender_item_id',
            field=models.CharField(default='201403140001', max_length=200),
        ),
    ]
