# Generated by Django 4.2 on 2023-06-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0009_blogarticle_slug'),
        ('Like', '0009_remove_payoutuserlist_lists_and_more'),
    ]

    operations = [
    ]
