# Generated by Django 4.2 on 2023-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0009_item_brand_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_keeping_unit',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
