# Generated by Django 4.2 on 2023-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0010_merge_20230615_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
