# Generated by Django 4.2 on 2023-08-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0011_contactformentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormEntry',
            new_name='BrandContactForm',
        ),
    ]
