# Generated by Django 4.2 on 2023-08-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0012_rename_contactformentry_brandcontactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandContactForm',
            new_name='ContactFormEntry',
        ),
    ]
