# Generated by Django 4.2 on 2023-08-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0015_contactmessage_delete_contactusformentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='email_1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='username',
            new_name='name',
        ),
    ]
