# Generated by Django 4.2 on 2023-08-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0018_rename_contactmessageentry_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactMessageEntry',
        ),
    ]
