# Generated by Django 3.2.20 on 2023-08-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0019_rename_contactmessage_contactmessageentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique_request',
            name='address',
            field=models.CharField(default='Default Business address', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(default='Default Business address', max_length=500),
        ),
    ]
