# Generated by Django 3.2.20 on 2023-10-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0021_auto_20231007_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(default='none', max_length=900),
        ),
        migrations.AddField(
            model_name='item',
            name='image0',
            field=models.CharField(blank=True, default='/static/images/banner3.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.CharField(blank=True, default='/static/images/banner3.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.CharField(blank=True, default='/static/images/banner3.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='none', max_length=900),
        ),
        migrations.AddField(
            model_name='item',
            name='size_name',
            field=models.CharField(default='none', max_length=900),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=0, max_length=2000),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_status',
            field=models.CharField(default='instock', max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.CharField(blank=True, default='/static/images/banner3.png', max_length=200, null=True),
        ),
    ]
