# Generated by Django 3.2.20 on 2023-10-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0022_auto_20231015_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2a',
            field=models.CharField(blank=True, default='/static/images/banner3.png', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, default='/static/images/banner3.png', null=True, upload_to=''),
        ),
    ]
